#pragma once

#define COMBAT_HP_PER_STR 10.0f
#define COMBAT_PHY_PER_STR 0.03f
#define COMBAT_MAG_PER_INT 0.03f
#define COMBAT_AFF_PER_INT 1.0f
#define COMBAT_ARM_PER_AGI 0.3f
#define COMBAT_SPD_PER_AGI 0.03f

#define COMBAT_BASE_HP 150.0f
#define COMBAT_ARMOR_REDUCTION 0.06f

