/***********************************************************************
   WARNING: This file generated by robots.  Do not attempt to modify.

   This API is for use with worldstate.db
   Which contains 1 table(s).
***********************************************************************/

#pragma once

#include "segautils/Defs.h"
#include "segautils/String.h"

typedef struct sqlite3_stmt sqlite3_stmt;
typedef struct lua_State lua_State;
typedef struct DB_worldstate DB_worldstate;

DB_worldstate *db_worldstateCreate();
void db_worldstateDestroy(DB_worldstate *self);
int db_worldstateCreateTables(DB_worldstate *self);

typedef struct {
   String *id;
} DBActor;

#define VectorTPart DBActor
#include "segautils/Vector_Decl.h"

void dbActorDestroy(DBActor *self); //this does not call free on self!!
int dbActorInsert(DB_worldstate *db, const DBActor *obj);
int dbActorUpdate(DB_worldstate *db, const DBActor *obj); //will base on primary key
vec(DBActor) *dbActorSelectAll(DB_worldstate *db);
DBActor dbActorSelectFirstByid(DB_worldstate *db, const char *id);
int dbActorDeleteAll(DB_worldstate *db);
int dbActorDeleteByid(DB_worldstate *db, const char *id);

